"""Initial migration with all tables

Revision ID: 391ace4de709
Revises: db0c953801d3
Create Date: 2025-09-09 03:09:53.783697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '391ace4de709'
down_revision: Union[str, Sequence[str], None] = 'db0c953801d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_table('worldviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('time_period', sa.String(), nullable=True),
    sa.Column('technology_level', sa.String(), nullable=True),
    sa.Column('magic_system', sa.Text(), nullable=True),
    sa.Column('additional_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worldviews_id'), 'worldviews', ['id'], unique=False)
    op.create_table('writing_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tone', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('point_of_view', sa.String(), nullable=True),
    sa.Column('reference_works', sa.Text(), nullable=True),
    sa.Column('guidelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_styles_id'), 'writing_styles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_styles_id'), table_name='writing_styles')
    op.drop_table('writing_styles')
    op.drop_index(op.f('ix_worldviews_id'), table_name='worldviews')
    op.drop_table('worldviews')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
