"""add new jsonb fields to character model

Revision ID: 67d97dd67785
Revises: bbe406c67418
Create Date: 2025-09-12 00:58:33.079701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app import database_types

# revision identifiers, used by Alembic.
revision: str = '67d97dd67785'
down_revision: Union[str, Sequence[str], None] = 'bbe406c67418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('body_details', postgresql.JSONB(astext_type=sa.Text()).with_variant(database_types.JsonEncodedDict(), 'sqlite'), nullable=True))
    op.add_column('characters', sa.Column('clothing_style_and_habits', postgresql.JSONB(astext_type=sa.Text()).with_variant(database_types.JsonEncodedDict(), 'sqlite'), nullable=True))
    op.add_column('characters', sa.Column('sexual_preferences_and_behaviors', postgresql.JSONB(astext_type=sa.Text()).with_variant(database_types.JsonEncodedDict(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'sexual_preferences_and_behaviors')
    op.drop_column('characters', 'clothing_style_and_habits')
    op.drop_column('characters', 'body_details')
    # ### end Alembic commands ###
