"""Add prompt_presets table

Revision ID: 747b10d7d104
Revises: 67d97dd67785
Create Date: 2025-09-12 08:13:30.333840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747b10d7d104'
down_revision: Union[str, Sequence[str], None] = '67d97dd67785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('cot_guidance', sa.Text(), nullable=True),
    sa.Column('other_instructions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_presets_id'), 'prompt_presets', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_presets_name'), 'prompt_presets', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_presets_name'), table_name='prompt_presets')
    op.drop_index(op.f('ix_prompt_presets_id'), table_name='prompt_presets')
    op.drop_table('prompt_presets')
    # ### end Alembic commands ###
