"""Initial migration with all tables

Revision ID: 77c66804195f
Revises: 391ace4de709
Create Date: 2025-09-09 05:00:21.196562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77c66804195f'
down_revision: Union[str, Sequence[str], None] = '391ace4de709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_outlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=True),
    sa.Column('target_word_count', sa.Integer(), nullable=True),
    sa.Column('worldview_id', sa.Integer(), nullable=True),
    sa.Column('writing_style_id', sa.Integer(), nullable=True),
    sa.Column('settings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outline_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worldview_id'], ['worldviews.id'], ),
    sa.ForeignKeyConstraint(['writing_style_id'], ['writing_styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_outlines_id'), 'generated_outlines', ['id'], unique=False)
    op.add_column('projects', sa.Column('book_title', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('core_concept', sa.Text(), nullable=True))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('projects', 'core_concept')
    op.drop_column('projects', 'book_title')
    op.drop_index(op.f('ix_generated_outlines_id'), table_name='generated_outlines')
    op.drop_table('generated_outlines')
    # ### end Alembic commands ###
