"""Add model_type to AIModel

Revision ID: 80428350cb3e
Revises: 747b10d7d104
Create Date: 2025-09-13 02:26:15.513398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80428350cb3e'
down_revision: Union[str, Sequence[str], None] = '747b10d7d104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


model_type_enum = sa.Enum('IMAGE_GENERATION', 'LANGUAGE_MODEL', 'MULTI_MODAL', 'OTHER', name='modeltype')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    model_type_enum.create(op.get_bind())
    op.add_column('ai_models', sa.Column('model_type', model_type_enum, server_default='LANGUAGE_MODEL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'model_type')
    model_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
