"""Initial migration with all tables

Revision ID: db0c953801d3
Revises: 1de6c234e616
Create Date: 2025-09-08 09:54:30.718549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0c953801d3'
down_revision: Union[str, Sequence[str], None] = '1de6c234e616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outline_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_brief', sa.Text(), nullable=True, comment='内容蓝图/写作指令'),
    sa.Column('generated_content', sa.Text(), nullable=True, comment='AI生成或用户最终编辑的内容'),
    sa.Column('word_count_target', sa.Integer(), nullable=True, comment='目标字数'),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='nodestatus'), nullable=False, comment='节点状态'),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_order', sa.Integer(), nullable=False, comment='排序字段'),
    sa.ForeignKeyConstraint(['parent_id'], ['outline_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outline_nodes_id'), 'outline_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_outline_nodes_parent_id'), 'outline_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_outline_nodes_project_id'), 'outline_nodes', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outline_nodes_project_id'), table_name='outline_nodes')
    op.drop_index(op.f('ix_outline_nodes_parent_id'), table_name='outline_nodes')
    op.drop_index(op.f('ix_outline_nodes_id'), table_name='outline_nodes')
    op.drop_table('outline_nodes')
    # ### end Alembic commands ###
